# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Tech Blog
subtitle: "Fiona's playground"
email: fiona_it@163.com
name: Fiona Zou
description: >
  This is Fiona's blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
ga_tracking_id: "fiona89"

# Category descriptions (for archive pages)
descriptions:
  - cat: life
    desc: "Share life stories."

  - cat: tech
    desc: "Share Tech article."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: Fi√¥na
    url: https://twitter.com/201903f
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: fiona
    url: https://github.com/fiona8953
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: 
    url: 
    desc: Connect with me on LinkedIn
    share: true

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username: 
    url: 
    desc: Follow me on Instagram
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/fiona8953/fiona8953.github.io"
    os_rcs_type: "git"
    os_src: "git@github.com:fiona8953/fiona8953.github.io"
